name: 'Pull Request to Slack'
on:
  pull_request:
    types: [review_requested, synchronize, closed]
  pull_request_review_comment:
    types: [created, edited]
  push:
jobs:
  github_to_slack:
    runs-on: ubuntu-latest
    name: Start
    steps:
      - name: Pull Request to Slack
        uses: sildeswj/github-to-slack@latest
        id: sildeswj
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github-run-id: ${{ github.run_id }}